### ISSUE TITLE
Havoc Pattern

### ISSUE THREAD

**Issue by hitch3ns** [sayoui001/ApexAHK-Reduce-recoil#1]
I tested Most of patterns all good. no issues on v5

the only one that require update is Havoc, Havoc turbo beaming though :D

**Comment by sayoui001** [comment]
> I tested Most of patterns all good. no issues on v5
> 
> the only one that require update is Havoc, Havoc turbo beaming though :D

Someone told me R99 pattern seem weird.

**Comment by hitch3ns** [comment]
> > I tested Most of patterns all good. no issues on v5
> > the only one that require update is Havoc, Havoc turbo beaming though :D
> 
> Someone told me R99 pattern seem weird.

yes better revert to this one for r99

{1: "-1.6,7,53",     2: "0.1,7.5,53",       3: "2.3,4.9,53"
               ,4: "-1.8,10,53",  5: "-3.3,15.4,53",   6: "-6.3,12,53"
               ,7: "-5.5,9.7,53",   8: "-2.5,10.8,53",    9: "0.2,11,52"
              ,10: "2.3,6.8,52",   11: "4.5,5.3,52",    12: "0.9,5.1,52"
              ,13: "1.6,9.5,52",   14: "-1.1,4,52",     15: "-4.9,1,52"
              ,16: "-2.3,1.8,52",  17: "-4.5,0.5,52",   18: "4,1.3,52"
              ,19: "0,0,52",       20: "2.5,0.7,52",    21: "3.5,0.7,52"
              ,22: "4,4,52",    23: "3.5,0,52",       24: "4.6,0,52"
              ,25: "2,0,52",      26: "2,0,52",        27: "-5,-4,52"
              ,28: "-5,4,52",      29: "-5,-4,52",     30: "0,4,52"}
