### ISSUE TITLE
Why do we need a subshootkey? To make the script safer?

### ISSUE THREAD

**Issue by mgsweet** [sayoui001/ApexAHK-Reduce-recoil#5]
https://github.com/sayoui001/ApexAHK-Reduce-recoil/blob/c9f8b97f1ac95ae19dd68bcf30a41e9cac253105/NickAR.ahk#L387

Great script and nice sharing. Really appreciate that. I will copy some parts of your code to improve mine so that I can reuse your pattern:)

**Comment by sayoui001** [comment]
Ya , just in case. Because old author put this in code. I think the game can detect spamming click .
